// DO NOT IMPORT IMAGES FROM ANYWHERE ELSE. All assets must be declared here.
export const ASSETS = {
  logos: {
    white: '/logo-letras-final-blanco.svg',
    dark: '/logo-letras-final-blanco.svg',
    iconWhite: '/logo-letras-final-blanco.svg',
  },
  hero: {
    main: '/hero-main.jpg',
  },
  thumbnails: {
    americanaUmbra: '/thumbnails/americana-umbra.jpg',
    bolsoMonogramaTambvrini: '/thumbnails/bolso-monograma-tambvrini.jpg',
    camisetaImperium: '/thumbnails/camiseta-imperium.jpg',
    camisetaSportClub: '/thumbnails/camiseta-sport-club.jpg',
    poloAureus: '/thumbnails/polo-aureus.jpg',
    poloDomus: '/thumbnails/polo-domus.jpg',
    poloGolf: '/thumbnails/polo-golf.jpg',
    poloPatricius: '/thumbnails/polo-patricius.jpg',
    poloRegius: '/thumbnails/polo-regius.jpg',
    sueterCaptain: '/thumbnails/sueter-captain.jpg',
    sueterSylva: '/thumbnails/sueter-sylva.jpg',
    trajeMonogramaTambvrini: '/thumbnails/traje-monograma-tambvrini.jpg',
  },
  products: {
    americanaUmbra: {
      images: [
        '/products/americana-umbra/1.jpg',
        '/products/americana-umbra/2.jpg',
        '/products/americana-umbra/3.jpg',
        '/products/americana-umbra/4.jpg',
        '/products/americana-umbra/5.jpg',
        '/products/americana-umbra/6.jpg',
        '/products/americana-umbra/7.jpg',
        '/products/americana-umbra/8.jpg',
        '/products/americana-umbra/9.jpg',
        '/products/americana-umbra/10.jpg',
        '/products/americana-umbra/11.jpg',
        '/products/americana-umbra/12.jpg',
      ],
    },
    bolsoMonogramaTambvrini: {
      images: [
        '/products/bolso-monograma-tambvrini/1.jpg',
        '/products/bolso-monograma-tambvrini/2.jpg',
        '/products/bolso-monograma-tambvrini/3.jpg',
        '/products/bolso-monograma-tambvrini/4.jpg',
        '/products/bolso-monograma-tambvrini/5.jpg',
        '/products/bolso-monograma-tambvrini/6.jpg',
        '/products/bolso-monograma-tambvrini/7.jpg',
        '/products/bolso-monograma-tambvrini/8.jpg',
        '/products/bolso-monograma-tambvrini/9.jpg',
        '/products/bolso-monograma-tambvrini/10.jpg',
        '/products/bolso-monograma-tambvrini/11.jpg',
      ],
    },
    camisetaImperium: {
      images: [
        '/products/camiseta-imperium/1.jpg',
        '/products/camiseta-imperium/2.jpg',
        '/products/camiseta-imperium/3.jpg',
        '/products/camiseta-imperium/4.jpg',
        '/products/camiseta-imperium/5.jpg',
        '/products/camiseta-imperium/6.jpg',
        '/products/camiseta-imperium/7.jpg',
        '/products/camiseta-imperium/8.jpg',
        '/products/camiseta-imperium/9.jpg',
        '/products/camiseta-imperium/10.jpg',
        '/products/camiseta-imperium/11.jpg',
        '/products/camiseta-imperium/12.jpg',
        '/products/camiseta-imperium/13.jpg',
        '/products/camiseta-imperium/14.jpg',
        '/products/camiseta-imperium/15.jpg',
        '/products/camiseta-imperium/16.jpg',
      ],
    },
    camisetaSportClub: {
      images: [
        '/products/camiseta-sport-club/1.jpg',
        '/products/camiseta-sport-club/2.jpg',
        '/products/camiseta-sport-club/3.jpg',
        '/products/camiseta-sport-club/4.jpg',
        '/products/camiseta-sport-club/5.jpg',
        '/products/camiseta-sport-club/6.jpg',
        '/products/camiseta-sport-club/7.jpg',
        '/products/camiseta-sport-club/8.jpg',
        '/products/camiseta-sport-club/9.jpg',
        '/products/camiseta-sport-club/10.jpg',
        '/products/camiseta-sport-club/11.jpg',
        '/products/camiseta-sport-club/12.jpg',
        '/products/camiseta-sport-club/13.jpg',
        '/products/camiseta-sport-club/14.jpg',
      ],
    },
    poloAureus: {
      images: [
        '/products/polo-aureus/1.jpg',
        '/products/polo-aureus/2.jpg',
        '/products/polo-aureus/3.jpg',
        '/products/polo-aureus/4.jpg',
        '/products/polo-aureus/5.jpg',
        '/products/polo-aureus/6.jpg',
        '/products/polo-aureus/7.jpg',
        '/products/polo-aureus/8.jpg',
        '/products/polo-aureus/9.jpg',
        '/products/polo-aureus/10.jpg',
      ],
    },
    poloDomus: {
      images: [
        '/products/polo-domus/1.jpg',
        '/products/polo-domus/2.jpg',
        '/products/polo-domus/3.jpg',
        '/products/polo-domus/4.jpg',
        '/products/polo-domus/5.jpg',
        '/products/polo-domus/6.jpg',
        '/products/polo-domus/7.jpg',
        '/products/polo-domus/8.jpg',
        '/products/polo-domus/9.jpg',
        '/products/polo-domus/10.jpg',
        '/products/polo-domus/11.jpg',
        '/products/polo-domus/12.jpg',
        '/products/polo-domus/13.jpg',
        '/products/polo-domus/14.jpg',
        '/products/polo-domus/15.jpg',
        '/products/polo-domus/16.jpg',
        '/products/polo-domus/17.jpg',
      ],
    },
    poloGolf: {
      images: [
        '/products/polo-golf/1.jpg',
        '/products/polo-golf/2.jpg',
        '/products/polo-golf/3.jpg',
        '/products/polo-golf/4.jpg',
        '/products/polo-golf/5.jpg',
        '/products/polo-golf/6.jpg',
        '/products/polo-golf/7.jpg',
        '/products/polo-golf/8.jpg',
        '/products/polo-golf/9.jpg',
        '/products/polo-golf/10.jpg',
        '/products/polo-golf/11.jpg',
        '/products/polo-golf/12.jpg',
        '/products/polo-golf/13.jpg',
      ],
    },
    poloPatricius: {
      images: [
        '/products/polo-patricius/1.jpg',
        '/products/polo-patricius/2.jpg',
        '/products/polo-patricius/3.jpg',
        '/products/polo-patricius/4.jpg',
        '/products/polo-patricius/5.jpg',
        '/products/polo-patricius/6.jpg',
        '/products/polo-patricius/7.jpg',
        '/products/polo-patricius/8.jpg',
        '/products/polo-patricius/9.jpg',
        '/products/polo-patricius/10.jpg',
        '/products/polo-patricius/11.jpg',
        '/products/polo-patricius/12.jpg',
        '/products/polo-patricius/13.jpg',
        '/products/polo-patricius/14.jpg',
        '/products/polo-patricius/15.jpg',
      ],
    },
    poloRegius: {
      images: [
        '/products/polo-regius/1.jpg',
        '/products/polo-regius/2.jpg',
        '/products/polo-regius/3.jpg',
        '/products/polo-regius/4.jpg',
        '/products/polo-regius/5.jpg',
        '/products/polo-regius/6.jpg',
        '/products/polo-regius/7.jpg',
        '/products/polo-regius/8.jpg',
        '/products/polo-regius/9.jpg',
        '/products/polo-regius/10.jpg',
        '/products/polo-regius/11.jpg',
        '/products/polo-regius/12.jpg',
        '/products/polo-regius/13.jpg',
        '/products/polo-regius/14.jpg',
        '/products/polo-regius/15.jpg',
        '/products/polo-regius/16.jpg',
        '/products/polo-regius/17.jpg',
        '/products/polo-regius/18.jpg',
      ],
    },
    sueterCaptain: {
      images: [
        '/products/sueter-captain/1.jpg',
        '/products/sueter-captain/2.jpg',
        '/products/sueter-captain/3.jpg',
        '/products/sueter-captain/4.jpg',
        '/products/sueter-captain/5.jpg',
        '/products/sueter-captain/6.jpg',
        '/products/sueter-captain/7.jpg',
        '/products/sueter-captain/8.jpg',
        '/products/sueter-captain/9.jpg',
        '/products/sueter-captain/10.jpg',
        '/products/sueter-captain/11.jpg',
        '/products/sueter-captain/12.jpg',
      ],
    },
    sueterSylva: {
      images: [
        '/products/sueter-sylva/1.jpg',
        '/products/sueter-sylva/2.jpg',
        '/products/sueter-sylva/3.jpg',
        '/products/sueter-sylva/4.jpg',
        '/products/sueter-sylva/5.jpg',
        '/products/sueter-sylva/6.jpg',
        '/products/sueter-sylva/7.jpg',
        '/products/sueter-sylva/8.jpg',
        '/products/sueter-sylva/9.jpg',
        '/products/sueter-sylva/10.jpg',
        '/products/sueter-sylva/11.jpg',
        '/products/sueter-sylva/12.jpg',
        '/products/sueter-sylva/13.jpg',
        '/products/sueter-sylva/14.jpg',
        '/products/sueter-sylva/15.jpg',
      ],
    },
    trajeMonogramaTambvrini: {
      images: [
        '/products/traje-monograma-tambvrini/01.jpeg',
        '/products/traje-monograma-tambvrini/02.png',
        '/products/traje-monograma-tambvrini/03.jpeg',
        '/products/traje-monograma-tambvrini/04.jpeg',
        '/products/traje-monograma-tambvrini/05.png',
        '/products/traje-monograma-tambvrini/1.jpg',
        '/products/traje-monograma-tambvrini/2.jpg',
        '/products/traje-monograma-tambvrini/3.jpg',
        '/products/traje-monograma-tambvrini/4.jpg',
        '/products/traje-monograma-tambvrini/5.jpg',
        '/products/traje-monograma-tambvrini/6.jpg',
        '/products/traje-monograma-tambvrini/7.jpg',
        '/products/traje-monograma-tambvrini/8.jpg',
        '/products/traje-monograma-tambvrini/9.jpg',
        '/products/traje-monograma-tambvrini/10.jpg',
        '/products/traje-monograma-tambvrini/11.jpg',
      ],
    },
  },
  home: {
    novedadesHombreBg: '/products/polo-golf/1.jpg',
    novedadesMujerBg: '/products/camiseta-imperium/1.jpg',
    dropEditorial: '/products/traje-monograma-tambvrini/01.jpeg',
    editorialHero: '/products/bolso-monograma-tambvrini/1.jpg',
    dropCampaign: '/products/camiseta-sport-club/1.jpg',
    editorialPolos: '/products/polo-aureus/1.jpg',
    editorialSueteres: '/products/sueter-sylva/1.jpg',
  },
  brand: {
    marble: '/hero-main.jpg',
    tennis: '/products/polo-golf/2.jpg',
    romanCardWhite: '/logo-letras-final-blanco.svg',
    romanCardBlack: '/logo-letras-final-blanco.svg',
  },
  shop: {
    mujerHero: '/products/camiseta-imperium/2.jpg',
    hombreCampaign: '/products/polo-golf/2.jpg',
  },
  videos: {
    brand: {
      cinematic: 'https://customer-assets.emergentagent.com/job_a24b6471-62bc-4793-aa50-779b82deb92e/artifacts/axoe4sux_VIDEO%20WEB%201.mp4',
    },
    home: {
      novedadesHombre: 'https://customer-assets.emergentagent.com/job_a24b6471-62bc-4793-aa50-779b82deb92e/artifacts/sbeaj2rx_video%20hombre.mp4',
      novedadesMujer: 'https://customer-assets.emergentagent.com/job_a24b6471-62bc-4793-aa50-779b82deb92e/artifacts/mzrddski_video%20mujer.mp4',
    },
    productHover: {
      trajeMonogramaTambvrini: 'https://customer-assets.emergentagent.com/job_a24b6471-62bc-4793-aa50-779b82deb92e/artifacts/tf3t88bp_loop%20final%20model.mp4',
      poloAureus: 'https://customer-assets.emergentagent.com/job_602a5873-5674-439a-a044-350968db276c/artifacts/2bvf26dc_0212%20%284%29%281%29.mp4',
      bolsoMonogramaTambvrini: 'https://customer-assets.emergentagent.com/job_ed531f3b-442c-4069-8f9a-a4817ba88a48/artifacts/ll0mphlg_0216%282%29.mp4',
      camisetaSportClub: 'https://customer-assets.emergentagent.com/job_ed531f3b-442c-4069-8f9a-a4817ba88a48/artifacts/4q03omes_0216%281%29.mp4',
      poloGolf: 'https://customer-assets.emergentagent.com/job_ed531f3b-442c-4069-8f9a-a4817ba88a48/artifacts/rrxcz0pq_0216.mp4',
      camisetaImperium: 'https://customer-assets.emergentagent.com/job_602a5873-5674-439a-a044-350968db276c/artifacts/5muj0dwx_0212%20%284%29.mp4',
      americanaUmbra: 'https://customer-assets.emergentagent.com/job_602a5873-5674-439a-a044-350968db276c/artifacts/eotmn5eb_0212%20%284%29%282%29.mp4',
      sueterCaptain: 'https://customer-assets.emergentagent.com/job_602a5873-5674-439a-a044-350968db276c/artifacts/pu3df808_0212%20%284%29.mp4',
    },
    shop: {
      mujerCinematic: 'https://customer-assets.emergentagent.com/job_14c68bcb-ef5d-44c9-b883-bd8d392c855c/artifacts/b92rzs04_ANUNCIO%20TAMBVRINI%203.mov',
      hombreCinematic: 'https://customer-assets.emergentagent.com/job_14c68bcb-ef5d-44c9-b883-bd8d392c855c/artifacts/nqiyik78_video%20final%20tambvrini%202.mov',
    },
  },
};
